package com.apm.Registration.eu.bi;

import java.util.ArrayList;
import java.util.List;

import com.apm.DiaryManagement.eu.entity.Client;
import com.apm.DiaryManagement.eu.entity.DiaryManagement;
import com.apm.DiaryManagement.eu.entity.Priscription;
import com.apm.InstantMessage.eu.entity.InstantMsg;
import com.apm.Master.eu.entity.Master;
import com.apm.Registration.eu.entity.UserProfile;
import com.apm.common.utils.Pagination;
import com.apm.common.web.common.helper.Access;
import com.apm.common.web.common.helper.LoginInfo;

public interface UserProfileDAO {

	int saveUserprofile(UserProfile userprofile,int clinicid);
	int deletepharmacyuser(String id);
	int updateUserprofile(UserProfile userprofile);
	int deleteUserprofile(int selectedid);
	
	int getUserprofileCount(String searchText,int clinicid,int usertype )throws Exception;

	UserProfile getUserprofileDetails(int selectedid);
	
	//ArrayList<UserProfile> getUserProfileList();
	
	ArrayList<UserProfile> getUserProfileList(Pagination pagination,String searchText,int clinicid,int usertype)throws Exception;
	boolean isColorExist(String diarycolor);
	ArrayList<String> getJobTitleList();
	
	ArrayList<UserProfile> getAllUsers(String usertype);
	public UserProfile getPharmacyUserbyId(String id);
	public int updatePharmacyUserbyId(UserProfile userProfile);
	int insertJobTitle(UserProfile userProfile, String jobTitle);
	List getPractitionerList(int id);
	boolean isMobileNoExist(String mobileNo);
	boolean isEmailIdExist(String emailId,String selectedid,String existEmailid);
	int saveDetailsUserprofile(UserProfile userprofile, int id);
	int savePractitionerToAdmin(UserProfile userprofile, String userId);
	int getUserprofileCount(int id);
	ArrayList<UserProfile> getUserProfileList(Pagination pagination,int id);
	ArrayList<UserProfile> getAllPractitioner(int id);
	String getFullName(String id);
	String getUserEmail(String id);
	ArrayList<UserProfile> getAllPractitioner(String searchClient, int id);
	String getClientID(int selectedid);
	String getAdminDbUserID(int selectedid);
	int deleteAdminUserprofile(String userid);
	int getPractitionerId(int selectedid);
	int saveAdminPassword(UserProfile userprofile);
	String getExistingEmailID(String selectedid);
	int updatePractitionerAdminData(String userid, String email,String mobile,String existingUserid);
	String getexistingUserid(int selectedid);
	int getDiaryUserId(String userId);
	Access getRoleAccess(String jobtitle);
	int updateUserAccess(Access access, int selectedid);
	Access getUserRoleAccess(String userId);
	public String getName(String id);	
	ArrayList<UserProfile> getVisitingPractitiner();
	ArrayList<Master> getJobGroupList(String string);
	ArrayList<Master> getUserJobTitleList(String selectedid);
	ArrayList<Master> getDoctorList();
	int getIdIfEmailExist(String email);
	public ArrayList<UserProfile> getUserprofileList();
	public ArrayList<UserProfile> getAllUserProfileList();
	UserProfile getPharmacyUserDetails(int clinicid);
	int updatePharmacyProfile(int clinicid,UserProfile userProfile);
	int saPharmacyUser(UserProfile userProfile);
	ArrayList<UserProfile> getAllPharmacyUserList();
	public int updatePractitionerToAdmin(UserProfile userprofile, String clinicid,String userID);
	Access getopdRollAccess(String jobtitle);
	Access getipdaccesss(String jobtitle);
	Access getAccountaccesss(String jobtitle);
	Access getEmraccesss(String jobtitle);
	Access getClientAccesss(String jobtitle);
	int getIdFromUserId(String userId);
	int checkOldPharmacyPwd(UserProfile userProfile, String clinicUserid, String userid, String pwd);
	int updatePharmacyUserPwdbyId(UserProfile userProfile);
	int updateAdminPharmacyUsrwd(UserProfile userProfile, String clinicUserid, String userId);
	ArrayList<Master> getLabnameList();
	int saveInJobTitle(UserProfile userprofile);
	int updateGlobalAccess(String jobtitle, String val);
	int updatewidegetstatus(String jobtitle, String val, String cname);
	int updateactiveinactive(String id, String val);
	boolean checkUserActive(String userid);
	String getWardIdsFromUserid(String userid);
	int updatewardid(String userid, String val);
	String getUserNameFromUserid(String string);
	int saveVisitingCosultant(UserProfile userProfile, int clinicid, String clinicName);
	ArrayList<UserProfile> getVisitingPractitinerList();
	int checkdralreadypresent(String id);
	int saveReferralDoctor(UserProfile userProfile);
	ArrayList<UserProfile> checkExistConsultant(String val);
	int checkExistConsultantName(String consultantname);
	ArrayList<UserProfile> getAllPractitionerList(String issurgeon, String isanesthesiologist, String isvisitingconsultant, String isrefered, String ismlc);
	ArrayList<Client> getAllAnethesiaList();
	String getReferalDrName(String surgeon);
	UserProfile getrefereddrinfo(String id);
	int updateReferralDoctor(UserProfile userProfile);
	int updateLocalUserAdmin(String userId, String confirm_pwd);
	String getIndentApprovelocations(String userid);
	int updateIndentLocations(String userid, String val);
	String getLocationFromDiciplineID(String diciplineName);
	int getPractIdFromReferenceId(String practitionerid);
	boolean checkisshowdiscount(int clinicid);
	UserProfile getUserIndivisualAccess(String userid);
	int updateuserindivisualstatus(String userid, String val, String string);
	int updatemiswidegetstatus(String userid, String val, String cname);
	Access getMisRoleaccess(String userid);
	ArrayList<UserProfile>	getallbirthdays(String clinicname,String date);
	ArrayList<UserProfile> getVisitingPractitinerListFromUser();
	int checkIsValidReg(UserProfile user , String id);
	ArrayList<UserProfile> getAllUserList();
	String getPharmacyFullname(String string);
	ArrayList<UserProfile> getAllPharmacyUserListNew();
	Priscription getpharmaAdminaccess();
	int updateUserWiseAccess(String userid,String val,String dbcol);
	DiaryManagement getMainAccessofUser(String userid);
	UserProfile getMainAccessByUserid(String userid);
	Access getXMLAccess(String clinicid,String filepath);
	String getUserFullNameFromId(String string);
	boolean supportAccess(String uesrid);
	UserProfile getIndivdualAccess(String userid);
	boolean getWeekVaccineAccess();
	int insertToUserPaymentReportNotes(LoginInfo loginInfo, String note, String date);
	boolean ifEntryExistUserPaymentReportNotes(String  userid,String date);
	int updateStatusUserPaymentReportNotes(LoginInfo loginInfo, String status, String date, String id, String notes);
	int getIdOfPaymentReportNotes(String userid, String date);
	UserProfile getPaymentReportNotesData(String id);
	int saveEmployeeDetails(UserProfile userprofile);
	int updatePayrollEmpaxtive(String userid, String val);
	String getConditionData(String location);
	ArrayList<UserProfile> getSurgenList(String string);
	int saveUserForMisAccess(String userId);
	boolean isExistInMisAccess(String userId);
	String getClinicLinkAddress(String clinicUserid);
}
